# Generated by Django 6.1.1 on 2026-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profle_image_url', models.TextField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
