# Generated by Django 6.1.1 on 2026-09-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
