# Generated by Django 6.1.1 on 2026-09-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_profile_display_name_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profle_image_url',
            new_name='profile_image_url',
        ),
    ]
